### ISSUE TITLE
Kortmarkører renderers hver gang der trykkes på Kort tab pane.

### ISSUE THREAD

**Issue by baffioso** [regiongis/cvrflyt#17]
Eventen der er bundet til map tab pane rendere markører hver gang der trykkes på den. Kan eventuelt implementeres sådan:

https://github.com/regiongis/regiongis.github.io/blob/c2c28d66537c421631854e525b4fdd2f8df54bb4/cvrflyt/js/app.js#L244-L247

**Comment by danielarnason** [comment]
Det samme sker, hvis man ændrer til en anden kommune. Markørerne fra den tidligere søgning bliver ikke slettet, før de nye læses ind.

Eksempel: Først læste jeg data ind for Egedal, og så skiftede jeg til Billund kommune.
![udklip](https://user-images.githubusercontent.com/4689650/47790047-811d4c00-dd16-11e8-85ae-0b3aebdeedb8.PNG)

**Comment by magloire** [comment]
Det må vi lige fixe.

**Comment by magloire** [comment]
Fixed. tak @baffioso , jeg brugte din kode og det virkede fint.
