### ISSUE TITLE
Løsningen "hænger"

### ISSUE THREAD

**Issue by danielarnason** [regiongis/cvrflyt#18]
@magloire Løsningen ser ud til at hænge. 

Spinnerne spinner bare løs uden, at man kommer videre.

I browserens konsol kan man se, at der er noget der går galt, men jeg kan ikke helt gennemskue, hvad det er.
![cvr_flyt_fejl](https://user-images.githubusercontent.com/4689650/47704548-4a670900-dc24-11e8-9d9c-7ace8465ca12.PNG)

@baffioso Kender du den slags fejl?

**Comment by magloire** [comment]
Det ser ud til at, det sql api der ikke virker.

**Comment by magloire** [comment]
prøv at kigge på "network" tab, og se om sql api returnerer noget.

**Comment by danielarnason** [comment]
Der er vist problemer med plads på serveren. Når jeg laver et api kald via browseren, så får jeg denne her meddelelse.
`jQuery33105726029273236424_1540975916779({"success":false,"message":"SQLSTATE[53100]: Disk full: 7 ERROR:  could not extend file \"base\/18246\/2618\": No space left on device\nHINT:  Check free disk space.","code":400,"auth_check":{"success":true,"session":null,"auth_level":false},"_execution_time":0.07});`

Jeg tjekker lige med Lars, hvad vi skal gøre. Jeg skriver bare her, når jeg har fundet ud af noget.

**Comment by danielarnason** [comment]
Løsningen virker igen. 
Det var rigtigt, at der manglede diskplads på serveren. Der var nogle backup filer, der fyldte for meget. Martin Høgh har ryddet op i dem og sat et script op, der sletter backup filer, som er mere end 10 dage gamle.
