### ISSUE TITLE
problem med ssl certificate på serveren 

### ISSUE THREAD

**Issue by magloire** [regiongis/cvrflyt#19]
drayton.mapcentia.com uses an invalid security certificate. The certificate expired on November 9, 2018, 10:00:17 PM GMT+1. The current time is November 12, 2018, 9:36 AM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

**Comment by danielarnason** [comment]
Det ser ud som et problem til Martin Høgh :)

Jeg sender det lige til ham og Lars.

**Comment by danielarnason** [comment]
Det burde være fikset nu.

**Comment by magloire** [comment]
Nu er serveren ned, tror jeg.

**Comment by danielarnason** [comment]
Det tror jeg, at du har ret i. Jeg har i hvert fald.

Jeg hiver lige fat i Lars og Martin igen.
