### ISSUE TITLE
Autoincrement på gid i cvr_fad

### ISSUE THREAD

**Issue by HenningJagd** [regiongis/cvrflyt#5]
Der mangler autoincrement på gid kolonnen i den nye fad tabel. Vi har ikke rettigheder til at ændre tabellen.

@baffioso vil du køre en kommando? Jeg tror følgende vil løse problemet:
```SQL
ALTER TABLE cvr.cvr_fad
ALTER COLUMN gid
SET DEFAULT nextval('cvr.cvr_fad_view_gid_seq'::regclass);
```

**Comment by baffioso** [comment]
@HenningJagd @ClockEnd  Så er SQL'en trykket af
